[project]
name = "test-new-folder-order-v3r1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "dotenv>=0.9.9",
    "mysql-connector-python>=9.2.0",
]
