[tool.poetry]
name = "test-new-folder-order-v2r1"
version = "0.1.0"
description = ""
authors = ["MaksimHome <voronovmaksim88@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
